GET http://localhost:3005/todos

###
POST http://localhost:3005/todo/new
Content-Type: application/json

{
    "text":"hookup with a girl"
}

###

PUT http://localhost:3005/todo/complete/647f0952f13328c5967a682c


###
DELETE http://localhost:3005/todo/delete/647ecd45efa26a4bbcfb3c37